### ISSUE TITLE
minSdk version 19 -> 16?

### ISSUE THREAD

**Issue by kylpo** [henrytao-me/livedata-ktx#5]
Just curious if `19` is a requirement for this lib. If not, mind lowering it to `16` to reach [~5%](https://developer.android.com/about/dashboards/) more people?

No worries if you'd rather not, I think I should be OK with a fork.

Thanks for the lib!

**Comment by henrytao-me** [comment]
Sure. Let me test it with 16 and bump new version.

**Comment by henrytao-me** [comment]
@kylpo Please try 0.1.17. Thanks.

**Comment by kylpo** [comment]
Works on my end. Thanks! 🙌
